/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

//This is the configuration for authentication, this was generated by AWS Amplify
//Learnt from: https://docs.amplify.aws/gen1/react/start/getting-started/installation/

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:ab9cded3-0eda-49ec-8fca-9b956a50bb6f",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_5YyfqQKke",
    "aws_user_pools_web_client_id": "2ph8esc5v6okip5p1pl191tbvt",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
